version: '3.7'

services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true" # Enable Traefik dashboard (accessible at http://<your-domain>/dashboard/)
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=forvaidya@gmail.com" # Replace with your email
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`dosa.devops-ranch.in`)" # Replace with your domain
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=myresolver"

  dosa:
    image: containous/whoami
    container_name: dosa
    restart: always
    networks:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dosa.rule=Host(`dosa.devops-ranch.in`)" # Replace with your subdomain
      - "traefik.http.routers.dosa.entrypoints=websecure"
      - "traefik.http.routers.dosa.tls.certresolver=myresolver"

networks:
  reverse-proxy:
    driver: bridge